### PR TITLE
Add mower and tests

### PR DESCRIPTION
**Pull request by markkelnar**
@dhaas46 here's a mower class I thought we could use.  And some tests that could be run with phpunit.

### CODE REVIEW

**Comment by dhaas46** [comment]
for the PHPUnit should i download it from sebastianbergmann's file or from the php website or does it matter? to be able to run the tests

**Comment by markkelnar** [comment]
Yes.  That's a great thing to get up and running.

If you have a place where you are running PHP code, like a docker or vagrant or on your laptop, then you should be able to get a phpunit running.

**Comment by dhaas46** [comment]
awesome ill merge it with the one I have on my computer.

**Comment by dhaas46** [comment]
nevermind disregard my last email

**Pull request merged**
